safe: true
lsi: false
pygments: true
markdown: redcarpet
auto: true
title: "哲的博客"
public_url: "http://zhengchuanzhe.github.com"
keywords: "android,xml,html,JavaScript,css,Github"
owner:
  name: "郑传哲"
  mail: "1563151758@qq.com"
disqus:
  short_name: "zcz"
paginate: 10
exclude: [start-jekyll.bat, Github.sln, Github.v11.suo]
